// Curated prototype roster for Engine v3. These are product balancing values,
// not claims of canonical fact. Each version is explicit and every active power
// is represented by at least one typed combat action.

import type { Character, CombatAction, DefenseProfile, Stats } from "./types";
import {
  BATMAN_TECHNIQUES,
  DARTH_VADER_TECHNIQUES,
  DOCTOR_DOOM_TECHNIQUES,
  GODZILLA_TECHNIQUES,
  HULK_TECHNIQUES,
  SPIDER_MAN_TECHNIQUES,
} from "./action-library";

const s = (partial: Partial<Stats>): Stats => ({
  strength: 50,
  speed: 50,
  durability: 50,
  battleIQ: 50,
  combatSkill: 50,
  range: 50,
  technology: 0,
  magic: 0,
  mentalResistance: 50,
  healing: 10,
  battlefieldControl: 50,
  stamina: 60,
  ...partial,
});

const d = (partial: Partial<DefenseProfile>): DefenseProfile => ({
  armor: 30,
  evasion: 30,
  controlResistance: 40,
  systemIntegrity: 0,
  resistances: {},
  ...partial,
});

const action = (a: CombatAction): CombatAction => a;

export const CHARACTERS: Character[] = [
  {
    id: "doctor-doom",
    name: "Doctor Doom",
    version: "Earth-616 standard armor",
    universe: "Marvel",
    accent: "#10b981",
    description:
      "Sorcerer-scientist monarch combining elite armor, layered force fields and high-order magic.",
    scale: 3,
    preferredRange: 2,
    stats: s({
      strength: 76,
      speed: 64,
      durability: 87,
      battleIQ: 97,
      combatSkill: 80,
      range: 90,
      technology: 98,
      magic: 91,
      mentalResistance: 94,
      healing: 35,
      battlefieldControl: 94,
      stamina: 86,
    }),
    defense: d({
      armor: 88,
      evasion: 56,
      controlResistance: 91,
      systemIntegrity: 90,
      criticalSystems: true,
      resistances: {
        physical: 0.62,
        energy: 0.68,
        mystical: 0.48,
        psychic: 0.75,
        chemical: 0.9,
      },
    }),
    abilities: ["sorcery", "force-fields", "teleportation", "technopathy", "powered-armor"],
    resistances: ["mind-control", "energy", "conventional", "chemical"],
    weaknesses: ["arrogance", "armor-systems"],
    environment: {
      homeArenaIds: ["latveria"],
      affinityTags: ["high-tech", "high-magic", "fortified", "urban"],
      vulnerabilityTags: [],
      traits: ["vacuum-safe", "sealed-environment", "darkvision", "urban-mobility"],
      timeAffinity: {},
    },
    actions: [
      action({
        id: "doom-arcane-bolt",
        name: "Arcane Bolt",
        kind: "attack",
        damageType: "mystical",
        minRange: 1,
        maxRange: 3,
        power: 82,
        accuracy: 0.79,
        staminaCost: 8,
        penetration: 0.62,
        control: 8,
        tags: ["magic", "ranged"],
        scalePiercing: 2,
        text: {
          hit: "Doctor Doom threads an arcane bolt through {target}'s defense.",
          miss: "{target} slips the first arcane sigil before it closes.",
        },
      }),
      action({
        id: "doom-armor-volley",
        name: "Armor Volley",
        kind: "attack",
        damageType: "energy",
        minRange: 1,
        maxRange: 3,
        power: 64,
        accuracy: 0.8,
        staminaCost: 6,
        penetration: 0.35,
        tags: ["technology", "ranged", "area"],
        scalePiercing: 1,
        text: {
          hit: "Doom's armor saturates the lane with repulsor fire.",
          miss: "The volley scorches the arena, but {target} escapes the centerline.",
        },
      }),
      action({
        id: "doom-technopathic-hex",
        name: "Technopathic Hex",
        kind: "control",
        damageType: "mystical",
        minRange: 1,
        maxRange: 3,
        power: 28,
        accuracy: 0.72,
        staminaCost: 12,
        control: 28,
        systemDamage: 22,
        penetration: 0.8,
        cooldown: 3,
        tags: ["magic", "tech-exploit", "system-attack"],
        scalePiercing: 2,
        text: {
          hit: "A technopathic hex crawls through {target}'s critical systems.",
          miss: "{target}'s systems reject Doom's first intrusion.",
        },
      }),
      action({
        id: "doom-crimson-bands",
        name: "Crimson Bands",
        kind: "control",
        damageType: "mystical",
        minRange: 0,
        maxRange: 2,
        power: 32,
        accuracy: 0.7,
        staminaCost: 13,
        control: 64,
        penetration: 0.78,
        cooldown: 2,
        tags: ["magic", "control", "containment"],
        canContain: true,
        scalePiercing: 2,
        text: {
          hit: "Crimson bands lock around {target} and tighten with every struggle.",
          miss: "{target} breaks the geometry before the bands fully form.",
        },
      }),
      action({
        id: "doom-force-field",
        name: "Layered Force Field",
        kind: "defense",
        damageType: "energy",
        minRange: 0,
        maxRange: 3,
        power: 0,
        accuracy: 1,
        staminaCost: 8,
        guard: 58,
        cooldown: 2,
        tags: ["defense", "force-field"],
        text: { hit: "Doom layers a force field over his armor." },
      }),
      action({
        id: "doom-teleport",
        name: "Tactical Teleport",
        kind: "mobility",
        damageType: "mystical",
        minRange: 0,
        maxRange: 3,
        power: 0,
        accuracy: 1,
        staminaCost: 7,
        distanceShift: -2,
        cooldown: 2,
        tags: ["mobility", "teleport"],
        text: { hit: "Doom vanishes and reappears at his preferred distance." },
      }),
      action({
        id: "doom-mystic-seal",
        name: "Mystic Seal",
        kind: "finisher",
        damageType: "mystical",
        minRange: 0,
        maxRange: 2,
        power: 42,
        accuracy: 0.82,
        staminaCost: 18,
        control: 70,
        penetration: 0.85,
        requiresTargetControlAbove: 48,
        canContain: true,
        tags: ["magic", "finisher", "containment"],
        scalePiercing: 3,
        text: {
          hit: "Doom completes the seal; the battlefield itself closes around {target}.",
          miss: "{target} tears free before the final rune locks.",
        },
      }),
    ],
    techniques: DOCTOR_DOOM_TECHNIQUES,
    victoryPaths: [
      {
        id: "doom-mystic",
        name: "Mystic Overwhelm",
        tags: ["magic", "control"],
        description: "Layers binding magic until the opponent is sealed or incapacitated.",
        actionIds: ["doom-crimson-bands", "doom-mystic-seal", "doom-arcane-bolt"],
        method: "containment",
      },
      {
        id: "doom-tech",
        name: "Systems Exploit",
        tags: ["tech-exploit", "planning"],
        description: "Finds a critical technological dependency and shuts it down.",
        actionIds: ["doom-technopathic-hex"],
        method: "incapacitation",
      },
      {
        id: "doom-attrition",
        name: "Fortress Attrition",
        tags: ["defense", "stamina"],
        description:
          "Uses wards, armor and ranged pressure until the opponent can no longer continue.",
        actionIds: ["doom-force-field", "doom-armor-volley"],
        method: "exhaustion",
      },
    ],
  },
  {
    id: "darth-vader",
    name: "Darth Vader",
    version: "Canon, peak suit-era",
    universe: "Star Wars",
    accent: "#ef4444",
    description:
      "A heavily armored Sith Lord with precognition, telekinesis and ruthless lightsaber efficiency.",
    scale: 2,
    preferredRange: 1,
    stats: s({
      strength: 74,
      speed: 68,
      durability: 74,
      battleIQ: 86,
      combatSkill: 94,
      range: 73,
      technology: 62,
      magic: 84,
      mentalResistance: 88,
      healing: 10,
      battlefieldControl: 84,
      stamina: 82,
    }),
    defense: d({
      armor: 72,
      evasion: 58,
      controlResistance: 82,
      systemIntegrity: 100,
      criticalSystems: true,
      resistances: {
        physical: 0.35,
        energy: 0.38,
        mystical: 0.12,
        psychic: 0.68,
        chemical: 0.28,
      },
    }),
    abilities: ["telekinesis", "precognition", "lightsaber", "force-barrier"],
    resistances: ["mind-control", "fear", "pain"],
    weaknesses: ["life-support-armor", "electrical-systems"],
    environment: {
      homeArenaIds: ["mustafar"],
      affinityTags: ["dark", "volcanic", "hazardous", "high-tech"],
      vulnerabilityTags: ["aquatic"],
      traits: ["vacuum-resistant", "sealed-environment", "darkvision", "heat-resistant"],
      timeAffinity: { night: 0.04 },
    },
    actions: [
      action({
        id: "vader-force-choke",
        name: "Force Choke",
        kind: "control",
        damageType: "psychic",
        minRange: 1,
        maxRange: 3,
        power: 34,
        accuracy: 0.77,
        staminaCost: 10,
        control: 48,
        penetration: 0.45,
        cooldown: 2,
        tags: ["force", "telekinesis", "control", "biological"],
        scalePiercing: 1,
        text: {
          hit: "Vader closes a telekinetic grip around {target} and begins to crush.",
          miss: "{target} breaks Vader's concentration before the grip stabilizes.",
        },
      }),
      action({
        id: "vader-saber-strike",
        name: "Lightsaber Execution",
        kind: "attack",
        damageType: "energy",
        minRange: 0,
        maxRange: 1,
        power: 82,
        accuracy: 0.86,
        staminaCost: 8,
        penetration: 0.86,
        tags: ["lightsaber", "close-combat", "finisher"],
        scalePiercing: 1,
        text: {
          hit: "Vader steps through the guard and drives his lightsaber home.",
          miss: "The red blade misses by inches as {target} gives ground.",
        },
      }),
      action({
        id: "vader-saber-throw",
        name: "Saber Throw",
        kind: "attack",
        damageType: "energy",
        minRange: 1,
        maxRange: 2,
        power: 58,
        accuracy: 0.76,
        staminaCost: 7,
        penetration: 0.72,
        cooldown: 2,
        tags: ["lightsaber", "ranged"],
        scalePiercing: 1,
        text: {
          hit: "Vader's spinning blade curves through {target}'s escape route.",
          miss: "{target} ducks beneath the returning saber.",
        },
      }),
      action({
        id: "vader-telekinetic-barrage",
        name: "Telekinetic Barrage",
        kind: "attack",
        damageType: "physical",
        minRange: 1,
        maxRange: 3,
        power: 58,
        accuracy: 0.78,
        staminaCost: 9,
        control: 20,
        tags: ["force", "telekinesis", "area"],
        scalePiercing: 1,
        text: {
          hit: "Vader turns the arena into a telekinetic barrage around {target}.",
          miss: "The debris field tears past as {target} escapes the crush zone.",
        },
      }),
      action({
        id: "vader-force-guard",
        name: "Force Guard",
        kind: "defense",
        damageType: "psychic",
        minRange: 0,
        maxRange: 3,
        power: 0,
        accuracy: 1,
        staminaCost: 7,
        guard: 36,
        cooldown: 2,
        tags: ["defense", "force"],
        text: { hit: "Vader braces behind a compressed wall of Force." },
      }),
      action({
        id: "vader-force-pull",
        name: "Force Pull",
        kind: "mobility",
        damageType: "psychic",
        minRange: 1,
        maxRange: 3,
        power: 0,
        accuracy: 0.78,
        staminaCost: 7,
        control: 14,
        distanceShift: 2,
        tags: ["force", "mobility", "telekinesis"],
        scalePiercing: 1,
        text: {
          hit: "Vader rips {target} into lightsaber range.",
          miss: "{target} anchors against the Force pull.",
        },
      }),
    ],
    techniques: DARTH_VADER_TECHNIQUES,
    victoryPaths: [
      {
        id: "vader-choke",
        name: "Force Choke",
        tags: ["force", "control"],
        description: "Immobilizes a vulnerable opponent and crushes them from range.",
        actionIds: ["vader-force-choke"],
        method: "incapacitation",
      },
      {
        id: "vader-saber",
        name: "Saber Execution",
        tags: ["close-combat", "lightsaber"],
        description: "Uses precognition and control to create one decisive lightsaber opening.",
        actionIds: ["vader-saber-strike", "vader-force-pull"],
        method: "knockout",
      },
      {
        id: "vader-terrain",
        name: "Telekinetic Barrage",
        tags: ["force", "area"],
        description: "Pins the target beneath a sustained storm of battlefield debris.",
        actionIds: ["vader-telekinetic-barrage"],
        method: "incapacitation",
      },
    ],
  },
  {
    id: "spider-man",
    name: "Spider-Man",
    version: "Earth-616, standard suit",
    universe: "Marvel",
    accent: "#e11d48",
    description:
      "An agile enhanced hero whose spider-sense, webs and improvisation let him survive far above his weight class.",
    scale: 2,
    preferredRange: 2,
    stats: s({
      strength: 70,
      speed: 86,
      durability: 62,
      battleIQ: 84,
      combatSkill: 76,
      range: 66,
      technology: 72,
      magic: 0,
      mentalResistance: 66,
      healing: 46,
      battlefieldControl: 83,
      stamina: 84,
    }),
    defense: d({
      armor: 28,
      evasion: 94,
      controlResistance: 68,
      systemIntegrity: 22,
      resistances: {
        physical: 0.18,
        energy: 0.08,
        mystical: 0,
        psychic: 0.15,
        chemical: 0.12,
      },
    }),
    abilities: ["spider-sense", "web-shooters", "wall-crawl", "improvisation"],
    resistances: ["surprise-attacks"],
    weaknesses: ["area-attacks", "extreme-scale", "heavy-attrition"],
    environment: {
      homeArenaIds: [],
      affinityTags: ["urban", "dense-cover"],
      vulnerabilityTags: ["vacuum", "aquatic"],
      traits: ["urban-mobility", "enhanced-senses", "aquatic-capable"],
      timeAffinity: {},
    },
    actions: [
      action({
        id: "spidey-blitz",
        name: "Spider Blitz",
        kind: "attack",
        damageType: "physical",
        minRange: 0,
        maxRange: 1,
        power: 54,
        accuracy: 0.9,
        staminaCost: 7,
        penetration: 0.12,
        tags: ["speed", "close-combat", "precision"],
        scalePiercing: 0,
        text: {
          hit: "Spider-Man lands a spider-sense-guided combination on {target}.",
          miss: "{target} absorbs the angle and Spider-Man has to disengage.",
        },
      }),
      action({
        id: "spidey-web-snare",
        name: "Web Snare",
        kind: "control",
        damageType: "physical",
        minRange: 1,
        maxRange: 2,
        power: 10,
        accuracy: 0.9,
        staminaCost: 5,
        control: 44,
        cooldown: 1,
        tags: ["web", "control", "containment"],
        canContain: true,
        scalePiercing: 0,
        text: {
          hit: "Layer after layer of webbing binds {target}'s movement.",
          miss: "{target} tears through the first web line before it anchors.",
        },
      }),
      action({
        id: "spidey-environmental-trap",
        name: "Environmental Trap",
        kind: "control",
        damageType: "environmental",
        minRange: 1,
        maxRange: 3,
        power: 34,
        accuracy: 0.58,
        staminaCost: 12,
        control: 52,
        penetration: 0.58,
        cooldown: 4,
        tags: ["planning", "environment", "upset-path"],
        canBattlefieldRemove: true,
        scalePiercing: 2,
        text: {
          hit: "Spider-Man turns the collapsing environment into a trap around {target}.",
          miss: "The improvised trap triggers a fraction too early.",
        },
      }),
      action({
        id: "spidey-impact-web",
        name: "Impact Web",
        kind: "attack",
        damageType: "physical",
        minRange: 1,
        maxRange: 2,
        power: 38,
        accuracy: 0.86,
        staminaCost: 5,
        control: 12,
        tags: ["web", "ranged", "precision"],
        scalePiercing: 0,
        text: {
          hit: "An impact web detonates across {target}'s face and joints.",
          miss: "The impact web bursts against empty terrain.",
        },
      }),
      action({
        id: "spidey-evasive-swing",
        name: "Evasive Swing",
        kind: "defense",
        damageType: "physical",
        minRange: 0,
        maxRange: 3,
        power: 0,
        accuracy: 1,
        staminaCost: 4,
        guard: 34,
        distanceShift: -1,
        tags: ["defense", "mobility", "spider-sense"],
        text: { hit: "Spider-sense fires and Spider-Man swings out of the kill zone." },
      }),
    ],
    techniques: SPIDER_MAN_TECHNIQUES,
    victoryPaths: [
      {
        id: "spidey-outlast",
        name: "Outlast & Restrain",
        tags: ["speed", "control"],
        description: "Avoids clean contact and layers webbing until the opponent is contained.",
        actionIds: ["spidey-web-snare", "spidey-evasive-swing"],
        method: "containment",
      },
      {
        id: "spidey-improvise",
        name: "Improvised Battlefield Exploit",
        tags: ["planning", "environment"],
        description: "Finds a narrow environmental route to incapacitation or battlefield removal.",
        actionIds: ["spidey-environmental-trap"],
        method: "battlefield-removal",
      },
      {
        id: "spidey-blitz-path",
        name: "Precision Blitz",
        tags: ["speed", "precision"],
        description:
          "Targets vulnerable joints and systems faster than the opponent can stabilize.",
        actionIds: ["spidey-blitz", "spidey-impact-web"],
        method: "knockout",
      },
    ],
  },
  {
    id: "hulk",
    name: "Hulk",
    version: "Earth-616, standard savage Hulk",
    universe: "Marvel",
    accent: "#7ee35a",
    description:
      "A regenerating gamma titan whose strength and resistance climb as the fight becomes more violent.",
    scale: 4,
    preferredRange: 0,
    stats: s({
      strength: 99,
      speed: 64,
      durability: 98,
      battleIQ: 42,
      combatSkill: 58,
      range: 52,
      technology: 0,
      magic: 0,
      mentalResistance: 62,
      healing: 96,
      battlefieldControl: 72,
      stamina: 99,
    }),
    defense: d({
      armor: 96,
      evasion: 42,
      controlResistance: 92,
      systemIntegrity: 0,
      resistances: {
        physical: 0.82,
        energy: 0.62,
        mystical: 0.2,
        psychic: 0.28,
        chemical: 0.48,
        environmental: 0.72,
      },
    }),
    abilities: ["rage-scaling", "regeneration", "thunderclap", "gamma-leap"],
    resistances: ["conventional", "pain", "radiation", "extreme-force"],
    weaknesses: ["high-order-magic", "specialized-chemical", "battlefield-removal"],
    environment: {
      homeArenaIds: [],
      affinityTags: ["open", "destructible", "hazardous"],
      vulnerabilityTags: ["vacuum"],
      traits: ["toxin-immune", "enhanced-senses", "environmentally-resilient"],
      timeAffinity: {},
    },
    actions: [
      action({
        id: "hulk-smash",
        name: "Hulk Smash",
        kind: "attack",
        damageType: "physical",
        minRange: 0,
        maxRange: 1,
        power: 96,
        accuracy: 0.7,
        staminaCost: 5,
        penetration: 0.5,
        control: 20,
        tags: ["strength", "close-combat", "rage"],
        scalePiercing: 2,
        text: {
          hit: "Hulk catches {target} and drives them through the arena.",
          miss: "Hulk's swing detonates the ground where {target} stood.",
        },
      }),
      action({
        id: "hulk-leap-smash",
        name: "Gamma Leap",
        kind: "attack",
        damageType: "physical",
        minRange: 1,
        maxRange: 3,
        power: 84,
        accuracy: 0.64,
        staminaCost: 7,
        penetration: 0.42,
        control: 18,
        distanceShift: 3,
        tags: ["strength", "mobility", "area"],
        scalePiercing: 2,
        text: {
          hit: "Hulk crosses the battlefield in one leap and crashes into {target}.",
          miss: "The leap misses, but the impact wave still tears apart the arena.",
        },
      }),
      action({
        id: "hulk-thunderclap",
        name: "Thunderclap",
        kind: "attack",
        damageType: "physical",
        minRange: 0,
        maxRange: 2,
        power: 72,
        accuracy: 0.82,
        staminaCost: 6,
        control: 34,
        tags: ["strength", "area", "ranged"],
        scalePiercing: 2,
        text: {
          hit: "Hulk's thunderclap turns the air itself into a weapon.",
          miss: "{target} escapes the center of the shockwave, barely.",
        },
      }),
      action({
        id: "hulk-ground-quake",
        name: "Ground Quake",
        kind: "control",
        damageType: "environmental",
        minRange: 0,
        maxRange: 2,
        power: 54,
        accuracy: 0.78,
        staminaCost: 6,
        control: 44,
        tags: ["area", "control", "strength"],
        scalePiercing: 2,
        text: {
          hit: "Hulk fractures the battlefield and knocks {target} out of position.",
          miss: "{target} stays ahead of the collapsing ground.",
        },
      }),
      action({
        id: "hulk-roar",
        name: "Rage Surge",
        kind: "defense",
        damageType: "physical",
        minRange: 0,
        maxRange: 3,
        power: 0,
        accuracy: 1,
        staminaCost: 0,
        guard: 22,
        heal: 8,
        cooldown: 3,
        tags: ["rage", "healing", "defense"],
        text: { hit: "Hulk's rage spikes; wounds close as his stance becomes heavier." },
      }),
    ],
    techniques: HULK_TECHNIQUES,
    victoryPaths: [
      {
        id: "hulk-smash-path",
        name: "SMASH",
        tags: ["strength", "close-combat"],
        description: "Closes the distance and ends the fight through overwhelming physical force.",
        actionIds: ["hulk-smash", "hulk-leap-smash"],
        method: "knockout",
      },
      {
        id: "hulk-attrition",
        name: "Regenerate & Overwhelm",
        tags: ["healing", "stamina"],
        description: "Regenerates through the opponent's offense until they are exhausted.",
        actionIds: ["hulk-roar", "hulk-smash"],
        method: "exhaustion",
      },
      {
        id: "hulk-shockwave",
        name: "Arena-Wide Shockwave",
        tags: ["area", "control"],
        description: "Removes evasive options with a thunderclap or battlefield-breaking quake.",
        actionIds: ["hulk-thunderclap", "hulk-ground-quake"],
        method: "incapacitation",
      },
    ],
  },
  {
    id: "batman",
    name: "Batman",
    version: "Prime Earth, standard patrol gear",
    universe: "DC",
    accent: "#60a5fa",
    description:
      "A peak-human tactician with elite stealth and gadgets. Default simulations grant no advance preparation.",
    scale: 1,
    preferredRange: 2,
    stats: s({
      strength: 54,
      speed: 61,
      durability: 58,
      battleIQ: 98,
      combatSkill: 95,
      range: 65,
      technology: 86,
      magic: 0,
      mentalResistance: 90,
      healing: 18,
      battlefieldControl: 88,
      stamina: 80,
    }),
    defense: d({
      armor: 54,
      evasion: 74,
      controlResistance: 76,
      systemIntegrity: 35,
      resistances: {
        physical: 0.28,
        energy: 0.18,
        mystical: 0,
        psychic: 0.42,
        chemical: 0.55,
      },
    }),
    abilities: ["gadgets", "stealth", "detective", "martial-arts"],
    resistances: ["fear", "mind-control"],
    weaknesses: ["human-durability", "extreme-scale", "area-attacks"],
    environment: {
      homeArenaIds: ["gotham-city"],
      affinityTags: ["urban", "dense-cover", "dark", "high-tech"],
      vulnerabilityTags: ["vacuum", "aquatic", "open"],
      traits: ["urban-mobility", "darkvision", "night-specialist", "sealed-environment"],
      timeAffinity: { night: 0.14, dusk: 0.06, day: -0.03 },
    },
    actions: [
      action({
        id: "batman-batarang",
        name: "Precision Batarang",
        kind: "attack",
        damageType: "physical",
        minRange: 1,
        maxRange: 2,
        power: 30,
        accuracy: 0.9,
        staminaCost: 3,
        penetration: 0.18,
        systemDamage: 10,
        tags: ["precision", "gadget", "ranged"],
        scalePiercing: 0,
        text: {
          hit: "Batman lands a precision batarang on {target}'s exposed point.",
          miss: "{target} turns away from the batarang's intended angle.",
        },
      }),
      action({
        id: "batman-emp",
        name: "EMP Charge",
        kind: "control",
        damageType: "energy",
        minRange: 1,
        maxRange: 2,
        power: 18,
        accuracy: 0.74,
        staminaCost: 7,
        control: 18,
        systemDamage: 28,
        penetration: 0.82,
        cooldown: 4,
        tags: ["tech-exploit", "gadget", "system-attack"],
        scalePiercing: 1,
        text: {
          hit: "Batman's EMP charge detonates across {target}'s systems.",
          miss: "The EMP discharges outside its effective radius.",
        },
      }),
      action({
        id: "batman-gas",
        name: "Specialized Gas Capsule",
        kind: "control",
        damageType: "chemical",
        minRange: 0,
        maxRange: 2,
        power: 24,
        accuracy: 0.68,
        staminaCost: 6,
        control: 42,
        penetration: 0.45,
        cooldown: 4,
        tags: ["chemical", "gadget", "upset-path"],
        scalePiercing: 1,
        text: {
          hit: "A concentrated gas capsule blooms around {target}'s breathing zone.",
          miss: "The gas cloud disperses before {target} takes a meaningful dose.",
        },
      }),
      action({
        id: "batman-explosive-gel",
        name: "Explosive Gel",
        kind: "attack",
        damageType: "environmental",
        minRange: 1,
        maxRange: 2,
        power: 44,
        accuracy: 0.72,
        staminaCost: 6,
        control: 18,
        penetration: 0.35,
        cooldown: 2,
        tags: ["gadget", "environment", "planning"],
        scalePiercing: 1,
        text: {
          hit: "Batman detonates pre-placed gel as {target} enters the marked lane.",
          miss: "{target} moves before the gel can shape the blast.",
        },
      }),
      action({
        id: "batman-smoke",
        name: "Smoke and Vanish",
        kind: "defense",
        damageType: "chemical",
        minRange: 0,
        maxRange: 3,
        power: 0,
        accuracy: 1,
        staminaCost: 4,
        guard: 36,
        distanceShift: -1,
        cooldown: 2,
        tags: ["stealth", "defense", "mobility"],
        text: { hit: "Batman breaks line of sight and relocates through the smoke." },
      }),
      action({
        id: "batman-grapnel-trap",
        name: "Grapnel Trap",
        kind: "control",
        damageType: "environmental",
        minRange: 1,
        maxRange: 2,
        power: 18,
        accuracy: 0.76,
        staminaCost: 5,
        control: 32,
        tags: ["gadget", "control", "environment", "upset-path"],
        canBattlefieldRemove: true,
        scalePiercing: 1,
        text: {
          hit: "A grapnel line redirects {target} into a structural trap.",
          miss: "{target} snaps the line before the trap can load.",
        },
      }),
      action({
        id: "batman-takedown",
        name: "Precision Takedown",
        kind: "finisher",
        damageType: "physical",
        minRange: 0,
        maxRange: 1,
        power: 48,
        accuracy: 0.9,
        staminaCost: 8,
        penetration: 0.28,
        requiresTargetHealthBelow: 32,
        tags: ["martial-arts", "precision", "finisher"],
        scalePiercing: 0,
        text: {
          hit: "Batman converts the opening into a precise incapacitating takedown.",
          miss: "{target} powers out before the takedown is secured.",
        },
      }),
    ],
    techniques: BATMAN_TECHNIQUES,
    victoryPaths: [
      {
        id: "batman-systems",
        name: "Systems Shutdown",
        tags: ["tech-exploit", "gadget"],
        description: "Disables a critical technological dependency with a precisely timed EMP.",
        actionIds: ["batman-emp"],
        method: "incapacitation",
      },
      {
        id: "batman-environment",
        name: "Environmental Containment",
        tags: ["planning", "environment"],
        description: "Uses terrain, grapnels and explosives to create a narrow containment route.",
        actionIds: ["batman-grapnel-trap", "batman-explosive-gel"],
        method: "battlefield-removal",
      },
      {
        id: "batman-chemical",
        name: "Chemical Incapacitation",
        tags: ["chemical", "upset-path"],
        description:
          "Lands a specialized chemical dose and survives long enough for it to take effect.",
        actionIds: ["batman-gas"],
        method: "incapacitation",
      },
      {
        id: "batman-precision-finish",
        name: "Precision Incapacitation",
        tags: ["martial-arts", "precision"],
        description:
          "Converts a carefully created opening into a nonlethal strike sequence that ends resistance.",
        actionIds: ["batman-takedown"],
        method: "knockout",
      },
    ],
  },
  {
    id: "godzilla",
    name: "Godzilla",
    version: "Heisei-era composite baseline",
    universe: "Toho",
    accent: "#a78bfa",
    description:
      "A skyscraper-scale kaiju with atomic ranged offense, extreme durability and rapid regeneration.",
    scale: 5,
    preferredRange: 2,
    stats: s({
      strength: 99,
      speed: 48,
      durability: 100,
      battleIQ: 58,
      combatSkill: 64,
      range: 94,
      technology: 0,
      magic: 24,
      mentalResistance: 90,
      healing: 94,
      battlefieldControl: 94,
      stamina: 100,
    }),
    defense: d({
      armor: 99,
      evasion: 24,
      controlResistance: 93,
      systemIntegrity: 0,
      resistances: {
        physical: 0.9,
        energy: 0.76,
        mystical: 0.08,
        psychic: 0.62,
        chemical: 0.9,
        environmental: 0.92,
      },
    }),
    abilities: ["atomic-breath", "nuclear-pulse", "regeneration", "kaiju-scale"],
    resistances: ["conventional", "energy", "mind-control", "chemical", "pain"],
    weaknesses: ["specialized-kaiju-weapons", "high-order-magic"],
    environment: {
      homeArenaIds: ["open-ocean"],
      affinityTags: ["aquatic", "open", "destructible", "storm-prone"],
      vulnerabilityTags: ["vacuum"],
      traits: ["aquatic", "toxin-immune", "enhanced-senses", "environmentally-resilient"],
      timeAffinity: {},
    },
    actions: [
      action({
        id: "godzilla-atomic-breath",
        name: "Atomic Breath",
        kind: "attack",
        damageType: "energy",
        minRange: 1,
        maxRange: 3,
        power: 100,
        accuracy: 0.75,
        staminaCost: 7,
        penetration: 0.74,
        control: 18,
        tags: ["atomic", "ranged", "area"],
        scalePiercing: 3,
        text: {
          hit: "Godzilla's atomic breath engulfs {target} and the terrain behind them.",
          miss: "The atomic beam shears across the arena as {target} escapes its core.",
        },
      }),
      action({
        id: "godzilla-tail-sweep",
        name: "Tail Sweep",
        kind: "attack",
        damageType: "physical",
        minRange: 0,
        maxRange: 1,
        power: 92,
        accuracy: 0.72,
        staminaCost: 4,
        control: 36,
        tags: ["kaiju", "area", "close-combat"],
        scalePiercing: 3,
        text: {
          hit: "Godzilla's tail sweeps {target} through a wall of debris.",
          miss: "The tail levels the surroundings, but {target} avoids direct contact.",
        },
      }),
      action({
        id: "godzilla-stomp",
        name: "Kaiju Stomp",
        kind: "attack",
        damageType: "physical",
        minRange: 0,
        maxRange: 1,
        power: 98,
        accuracy: 0.62,
        staminaCost: 3,
        penetration: 0.55,
        control: 48,
        tags: ["kaiju", "strength", "area"],
        scalePiercing: 3,
        text: {
          hit: "Godzilla brings his full mass down on {target}'s position.",
          miss: "The stomp creates a crater as {target} escapes the footprint.",
        },
      }),
      action({
        id: "godzilla-nuclear-pulse",
        name: "Nuclear Pulse",
        kind: "attack",
        damageType: "energy",
        minRange: 0,
        maxRange: 2,
        power: 88,
        accuracy: 0.94,
        staminaCost: 12,
        control: 34,
        penetration: 0.58,
        cooldown: 3,
        tags: ["atomic", "area", "anti-evasion"],
        scalePiercing: 3,
        text: {
          hit: "A nuclear pulse erupts from Godzilla and erases every nearby escape lane.",
          miss: "{target} reaches the fringe of the pulse before it peaks.",
        },
      }),
      action({
        id: "godzilla-advance",
        name: "Relentless Advance",
        kind: "mobility",
        damageType: "environmental",
        minRange: 1,
        maxRange: 3,
        power: 18,
        accuracy: 1,
        staminaCost: 1,
        distanceShift: 1,
        control: 10,
        tags: ["kaiju", "mobility", "pressure"],
        scalePiercing: 3,
        text: { hit: "Godzilla advances through the terrain as though it is not there." },
      }),
      action({
        id: "godzilla-regenerate",
        name: "Kaiju Regeneration",
        kind: "defense",
        damageType: "physical",
        minRange: 0,
        maxRange: 3,
        power: 0,
        accuracy: 1,
        staminaCost: 0,
        guard: 24,
        heal: 12,
        cooldown: 3,
        tags: ["regeneration", "defense"],
        text: { hit: "Godzilla's damaged tissue knits together beneath glowing dorsal plates." },
      }),
    ],
    techniques: GODZILLA_TECHNIQUES,
    victoryPaths: [
      {
        id: "godzilla-breath",
        name: "Atomic Annihilation",
        tags: ["atomic", "ranged"],
        description: "Removes the opponent's safe space with sustained atomic breath.",
        actionIds: ["godzilla-atomic-breath", "godzilla-nuclear-pulse"],
        method: "knockout",
      },
      {
        id: "godzilla-stomp-path",
        name: "Kaiju Overrun",
        tags: ["kaiju", "strength"],
        description: "Closes distance and wins through overwhelming scale and mass.",
        actionIds: ["godzilla-stomp", "godzilla-tail-sweep", "godzilla-advance"],
        method: "knockout",
      },
      {
        id: "godzilla-attrition",
        name: "Immovable Apex",
        tags: ["regeneration", "stamina"],
        description: "Regenerates through all meaningful offense until the opponent is exhausted.",
        actionIds: ["godzilla-regenerate"],
        method: "exhaustion",
      },
    ],
  },
];

export const CHARACTERS_BY_ID: Record<string, Character> = Object.fromEntries(
  CHARACTERS.map((c) => [c.id, c]),
);

export function getCharacter(id: string | undefined | null): Character | undefined {
  if (!id) return undefined;
  return CHARACTERS_BY_ID[id];
}
